---
:consumer_key: mJ5otbhPGNoDCgCL7j5g
:consumer_secret: M0XkT6GeBnjxdlWHcSGYX1JutMVS9D5ISlkqRfShg
:access_token: 3130475392-rBIeqaTb7kRSIwG7mU8XkIaDdaULmmlw9FCLCdd
:access_token_secret: hvMt5VN9FK5XQnwR2DkZ2MX8up9tkH9VQz7CdQidnxfeI
